vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO aholzinger/nmos-cpp
	REF 98a13ee14f4b5150f7dcb1942563c521f5d2ee26
	SHA512 afdfb94bdf32ed89e86d85d749c38d59110c0d596e8b3d302e14a91305da4afb9b99692b4221554b7a782494bf448abf63eef1be2d53e47412c4a9ec64b5fc96
    HEAD_REF master
)

set (NMOS_CPP_OPTIONS_DEBUG)
set (NMOS_CPP_OPTIONS_RELEASE)

set (NMOS_CPP_OPTIONS_INCLUDE_PREFIX "-DNMOS_CPP_INCLUDE_PREFIX=/nmos-cpp")
set (NMOS_CPP_OPTIONS_PLATFORM_LIBS)
set (NMOS_CPP_OPTIONS_USE_CONAN "-DUSE_CONAN=OFF")
set (NMOS_CPP_OPTIONS_USE_VCPKG "-DUSE_VCPKG=ON")
set (NMOS_CPP_OPTIONS_USE_STATIC_RUNTIME)
set (NMOS_CPP_OPTIONS_WEBSOCKETPP_INCLUDE_DIR)
set (NMOS_CPP_LINKAGE_SUFFIX)


if (DEFINED VCPKG_TARGET_IS_WINDOWS AND ${VCPKG_TARGET_IS_WINDOWS} STREQUAL "1")
    if (${VCPKG_CRT_LINKAGE} STREQUAL "static")
        set (NMOS_CPP_OPTIONS_USE_STATIC_RUNTIME "-DUSE_STATIC_RUNTIME=ON")
        set (NMOS_CPP_OPTIONS_DEBUG "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebug")
        set (NMOS_CPP_OPTIONS_RELEASE "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded")
    else()
        if (${VCPKG_CRT_LINKAGE} STREQUAL "dynamic")
            set (NMOS_CPP_OPTIONS_PLATFORM_LIBS -DPLATFORM_LIBS="Winhttp.lib;httpapi.lib;bcrypt.lib;crypt32.lib")
            set (NMOS_CPP_OPTIONS_USE_STATIC_RUNTIME "-DUSE_STATIC_RUNTIME=OFF")
            set (NMOS_CPP_OPTIONS_DEBUG "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDebugDLL")
            set (NMOS_CPP_OPTIONS_RELEASE "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL")
        endif()
    endif()
else()
    # not yet tested
    # perhaps this isn't necessary
    if (DEFINED VCPKG_TARGET_IS_LINUX AND ${VCPKG_TARGET_IS_LINUX} STREQUAL "1")
        set(NMOS_CPP_OPTIONS_WEBSOCKETPP_INCLUDE_DIR "-DWEBSOCKETPP_INCLUDE_DIR=${VCPKG_ROOT_PATH}/packages/websocketpp_${VCPKG_TARGET_ARCHITECTURE}-linux${NMOS_CPP_LINKAGE_SUFFIX}/include/websocketpp")
    endif()
endif()

set(CMAKE_POLICY_DEFAULT_CMP0074 NEW)
set(CMAKE_POLICY_DEFAULT_CMP0091 NEW)

set(OPTIONS)
vcpkg_configure_cmake(
    SOURCE_PATH "${SOURCE_PATH}/Development"
    PREFER_NINJA
	OPTIONS
        ${NMOS_CPP_OPTIONS_INCLUDE_PREFIX}
        ${NMOS_CPP_OPTIONS_USE_CONAN}
        ${NMOS_CPP_OPTIONS_USE_VCPKG}
        ${NMOS_CPP_OPTIONS_USE_STATIC_RUNTIME}
        ${NMOS_CPP_OPTIONS_PLATFORM_LIBS}
        ${NMOS_CPP_OPTIONS_WEBSOCKETPP_INCLUDE_DIR}
    OPTIONS_DEBUG
        ${NMOS_CPP_OPTIONS_DEBUG}
    OPTIONS_RELEASE
        ${NMOS_CPP_OPTIONS_RELEASE}
)

vcpkg_install_cmake()

message(STATUS "CURRENT_PACKAGES_DIR = ${CURRENT_PACKAGES_DIR}")

# vcpkg_fixup_cmake_targets(CONFIG_PATH share/nmos-cpp)
# vcpkg_fixup_cmake_targets()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share ${CURRENT_PACKAGES_DIR}/share)

file(INSTALL
    ${SOURCE_PATH}/LICENSE
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/nmos-cpp RENAME copyright)

vcpkg_copy_pdbs()
